### ISSUE TITLE
why "CellTagV1_2" was selected in drawSubnet

### ISSUE THREAD

**Issue by lizhaozhi** [morris-lab/BiddyetalWorkflow#6]
Hi,

I noticed that in the `drawSubnet` function, you've chosen to use `tag = "CellTagV1_2"`. Was there a specific reason for this choice? Additionally, does the figure in the paper also use "CellTagV1_2"?

drawSubnet(tag = "CellTagV1_2", overlay = "Cluster", linkList = linkList, Nodes = Nodes )

From what I understand, "CellTagV1_1" is the largest and most diverse clone. I'm curious as to why "CellTagV1_2" was selected instead.

Thank you.

**Comment by sam-morris** [comment]
Hi - CellTagV1_2 refers to the second round of barcoding, after reprogramming is initiated. That one was selected to assess lineage following reprogramming initiation. CellTagV1_1 labels the initial fibroblast population. Hope that is helpful.
