### ISSUE TITLE
iEP QuadProg code

### ISSUE THREAD

**Issue by sachitsaksena** [morris-lab/BiddyetalWorkflow#7]
Hi all, thanks for the great paper on CellTag. In what script is the iEP identity score computed as described in Biddy et al. 2018: "The R package QuadProg was used for quadratic programming to generate cell identity scores."?

Thanks for the help!

**Comment by sam-morris** [comment]
Hi - I just uploaded a R markdown file to https://github.com/morris-lab/BiddyetalWorkflow/tree/master/scripts. You might also want to take a look at https://github.com/morris-lab/Capybara, which is based on the QP approach.

**Comment by sachitsaksena** [comment]
Thank you @sam-morris! And will do.

**Comment by sachitsaksena** [comment]
Sorry, just took a look and the imported script: "/scratch/smlab/CellTag_paper_analysis/quad_prog/src/quad_prog_collective_functions.R" is not available.

Alternatively, if you could point me to the metadata with iEP identity scores generated for Figure 1f of the 10X timecourse in the paper, that would be helpful!

Thanks again @sam-morris!
